---
- name: Render ECR Template
  template: src=ecr.json.j2 dest=rendered_templates/ecr.json

- name: Create ECR Stack
  cloudformation:
    stack_name: "{{stack_prefix}}-ecr"
    state: present
    region: "{{region}}"
    disable_rollback: true
    template: rendered_templates/ecr.json
    tags:
      Stack: "{{stack_prefix}}-ecr"

  register: ecr_stack
